name: Fork Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜执行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.fork-sync-pat }}  

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.fork-sync-pat }} 
          upstream_sync_repo: huangxd-/danmu_api
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false

      - name: Check for new commits
        if: success()
        run: echo "✅ Sync completed successfully"

      - name: Check for Failure
        if: failure()
        run: |
          echo "❌ [Error] Sync failed. Possible reasons:"
          echo "1. Upstream modified workflow files (requires PAT with 'workflows' permission)"
          echo "2. Merge conflicts needing manual resolution"
          echo "3. Network or token permission issues"
          exit 1
